### ISSUE TITLE
pfSense LDAP doesn't work without CA set

### ISSUE THREAD

**Issue by Hakujou** [opoplawski/ansible-pfsense#15]
Hello,

Without any CA set, we can't add an ldap server to pfsense without triggering an error.
With the following role:
```
- name: Setup LDAP
  pfsense_authserver_ldap:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    port: "{{ item.port }}"
    transport: "{{ item.transport }}"
    scope: subtree
    basedn: "{{ item.basedn }}"
    binddn: "{{ item.binddn }}"
    bindpw: "{{ item.bindpw }}"
    authcn: "{{ item.authcn }}"
    attr_user: samAccountName
    attr_member: memberOf
    attr_groupobj: group
    state: present
  with_items:
  - "{{ pfsense_ad }}"
```

I get the following error:
```
failed: [gw-dmz] (item={u'binddn': u'browse', u'name': u'AD', u'basedn': u'<redacted>', u'host': u'my_ad_server.domain.com', u'bindpw': u'<redacted>', u'scope': u'subtree', u'port': 389, u'transport': u'tcp', u'authcn': u'<redacted>'}) => {"changed": false, "item": {"authcn": "<redacted>", "basedn": "<redacted>", "binddn": "browse", "bindpw": "<redacted>", "host": "my_ad_server.domain.com", "name": "AD", "port": 389, "scope": "subtree", "transport": "tcp"}, "msg": "could not find CA 'None'"}
```

As you can see, CA field was never set (and it should not be required since it's a TCP connection on 389 without encryption).
