### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by tvories** [opoplawski/ansible-pfsense#19]
I was able to get everything connected and configured but when I try to set an alias or any other setting I get Permision denied.

I made sure the user I created has full admin access to my pfSense router.

Here is the exact output of the playbook:
```
PLAY [pfSense Testing] *************************************************************************************************************************************************************************************************************************************************************************
TASK [Gathering Facts] *************************************************************************************************************************************************************************************************************************************************************************ok: [192.168.1.1] 

TASK [Test Group] ******************************************************************************************************************************************************************************************************************************************************************************fatal: [192.168.1.1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.1.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1557281188.07-38654084696534/AnsiballZ_pfsense_alias.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1557281188.07-38654084696534/AnsiballZ_pfsense_alias.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1557281188.07-38654084696534/AnsiballZ_pfsense_alias.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_pfsense_alias_payload_WcBCE0/__main__.py\", line 93, in <module>\r\n  File \"/tmp/ansible_pfsense_alias_payload_WcBCE0/__main__.py\", line 89, in main\r\n  File \"/tmp/ansible_pfsense_alias_payload_WcBCE0/ansible_pfsense_alias_payload.zip/ansible/module_utils/networking/pfsense/pfsense_alias.py\", line 181, in commit_changes\r\n  File \"/tmp/ansible_pfsense_alias_payload_WcBCE0/ansible_pfsense_alias_payload.zip/ansible/module_utils/networking/pfsense/pfsense.py\", line 435, in write_config\r\n  File \"/usr/local/lib/python2.7/shutil.py\", line 316, in move\r\n    copy2(src, real_dst)\r\n  File \"/usr/local/lib/python2.7/shutil.py\", line 144, in copy2\r\n    copyfile(src, dst)\r\n  File \"/usr/local/lib/python2.7/shutil.py\", line 97, in copyfile\r\n    with open(dst, 'wb') as fdst:\r\nIOError: [Errno 13] Permission denied: '/cf/conf/config.xml'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
        to retry, use: --limit @/home/tadmin/ansibletesting/ansible-pfsense/test.retry

PLAY RECAP *************************************************************************************************************************************************************************************************************************************************************************************192.168.1.1                : ok=1    changed=0    unreachable=0    failed=1
```

And here is my playbook:

```yaml
---

- name: pfSense Testing
  hosts: pfsense

  tasks:
    - name: Test Group
      pfsense_alias:
              name: "Test1"
              address: 10.9.92.1
              type: host
              state: present
```

**Comment by opoplawski** [comment]
What user are you connecting as?  What is the output of "ls -l /cf/conf/config.xml" on the pfsense box?

**Comment by tvories** [comment]
I am logged in as a user I created called `ansible`.  I gave it admin permissions on the web ui.  Output of ls:
```
/home/ansible: ls -l /cf/conf/config.xml  
-rw-r--r--  1 root  wheel  147342 May  7 20:07 /cf/conf/config.xml
```

**Comment by opoplawski** [comment]
You are going to have to set become to true (in ansible.cfg or your play) or connect as root.

**Comment by tvories** [comment]
That did it by logging in as root.  Become true didn't work.  It said sudo not found.

**Comment by opoplawski** [comment]
FWIW - I configure sudo with:
```
  - name: "Install packages"
    package:
      name:
        - pfSense-pkg-sudo
      state: present

  # Need to include sudoers.d in the GUI
  - name: "Give NWRA Domain Admins sudo rights"
    copy:
      dest: /usr/local/etc/sudoers.d/nwra-admin
      owner: root
      group: wheel
      mode: 0440
      content: |
        %Domain\ Admins             ALL=(ALL) NOPASSWD: ALL
```
Obviously you would need to adapt for your setup.
