### ISSUE TITLE
[Feature Request] Refactor to work with ansible galaxy

### ISSUE THREAD

**Issue by tvories** [opoplawski/ansible-pfsense#30]
## Overview
I have forked this project and attempted to refactor it to work with ansible galaxy collections.  This will allow users to install this module like they would a role.  This requires Ansible 2.9+ in order to install.

## Current issues
I am working out of the `galaxy` branch of my fork https://github.com/tvories/ansible-pfsense/tree/galaxy 

I have compiled a local version of the refactored code using `ansible-galaxy build` (specifically using ansible 2.10-dev).  That gives me a tar.gz of the plugin that I can install in my ansible project using `ansible-galaxy collection install opoplawski-pfsense-1.0.0.tar.gz`.

### My playbook:

```yaml
# pfsense.yml
---

- name: Pfsense Rules
  hosts: pfsense
  become: true

  roles:
    - pfsense
```

### The role:

```yaml
# roles/pfsense/tasks/vlans.yml
---

# VLAN Configuration

- name: 192.168.1.0/24 - Legacy
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 1
    descr: 192.168.1.0/24 - Legacy
    state: present

- name: 192.168.20.0/24 - Primary
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 20
    descr: 192.168.20.0/24 - Primary
    state: present

- name: 192.168.40.0/24 - Guest WiFi
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 40
    descr: 192.168.40.0/24 - Guest WiFi
    state: present

- name: 192.168.50.0/24 - IoT
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 50
    descr: 192.168.50.0/24 - IoT
    state: present

- name: 192.168.60.0/24 - DMZ
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 60
    descr: 192.168.60.0/24 - DMZ
    state: present

- name: 192.168.70.0/24 - Joey Backup
  opoplawski.pfsense.pfsense_vlan:
    interface: "{{ pfsense_lan_nic }}"
    vlan_id: 70
    descr: 192.168.70.0/24 - Joey Backup
    state: present
```

### The error
The module appears to import properly after the refactoring.  When I run `ansible-playbook pfsense.yml` I get the following error:

`ansible_collections.opoplawski.pfsense.plugins.module_utils.network.pfsense.pfsense_vlan.__spec__ is None`

I am not familiar with developing ansible modules, so I'm hoping this is just a mistake on the refactoring on my part.

The full ansible output:
```
PLAY [Pfsense Rules] ***********************************************************

TASK [Gathering Facts] *********************************************************
ok: [pfsense.mcbadass.local]

TASK [pfsense : include_tasks] *************************************************
included: /ansible/playbooks/roles/pfsense/tasks/vlans.yml for pfsense.mcbadass.local

TASK [pfsense : 192.168.1.0/24 - Legacy] ***************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: ansible_collections.opoplawski.pfsense.plugins.module_utils.network.pfsense.pfsense_vlan.__spec__ is None
fatal: [pfsense.mcbadass.local]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP *********************************************************************
pfsense.mcbadass.local     : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
