### ISSUE TITLE
New rules are disabled by default

### ISSUE THREAD

**Issue by opoplawski** [opoplawski/ansible-pfsense#41]
If I add a new rule, e.g.:
```
  - name: "Add force proxy rule"
    pfsense_rule:
      name: "Force proxy for some hosts"
      action: block
      interface: lan
      ipprotocol: inet
      protocol: tcp
      source: "force_proxy"
      destination: "any:web_ports"
      before: "Allow http"
      log: yes
      tracker: "0100002000"
      state: present
```
It gets added in a disabled state.
