### ISSUE TITLE
Unsupported parameters for (setup) module: gather_subset, gather_timeout

### ISSUE THREAD

**Issue by lhanson** [opoplawski/ansible-pfsense#44]
I'm trying to get basic setup functionality working for the following play:

```
- name: Configure pfSense
  hosts: pfsense
  remote_user: 'root'
  collections:
    - pfsensible.core
  tasks:
    - name: General setup
      pfsensible.core.setup:
        timezone: America/Chicago
```
I've installed the collection via `ansible-galaxy collection install pfsensible.core -p ./collections` and have set `collections_paths = collections` in `ansible.cfg`.

The setup module fails with the following error:
```
$ ansible-playbook --inventory hosts pfsense.yml

PLAY [Configure pfSense] ******************************************************************************************

TASK [Gathering Facts] ********************************************************************************************
fatal: [pfsense]: FAILED! => changed=false 
  ansible_facts: {}
  failed_modules:
    setup:
      ansible_facts:
        discovered_interpreter_python: /usr/local/bin/python2.7
      failed: true
      invocation:
        module_args:
          gather_subset:
          - all
          gather_timeout: 10
      msg: 'Unsupported parameters for (setup) module: gather_subset, gather_timeout Supported parameters include: dashboardavailablewidgetspanel, dashboardcolumns, disablealiaspopupdetail, dns_addresses, dns_gateways, dns_hostnames, dnsallowoverride, dnslocalhost, domain, hostname, interfacessort, language, logincss, loginshowhost, requirestatefilter, roworderdragging, statusmonitoringsettingspanel, systemlogsfilterpanel, systemlogsmanagelogpanel, timeservers, timezone, webguicss, webguifixedmenu, webguihostnamemenu, webguileftcolumnhyper'
  msg: |-
    The following modules failed to execute: setup

PLAY RECAP ********************************************************************************************************
pfsense                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
Version information from the pfSense web UI:
```
2.4.4-RELEASE-p3 (amd64)
built on Wed May 15 18:53:44 EDT 2019
FreeBSD 11.2-RELEASE-p10

The system is on the latest version.
Version information updated at Mon Mar 23 19:05:18 UTC 2020
```

**Comment by lhanson** [comment]
After some googling, I discovered that `gather_subset` and `gather_timeout` are part of the built-in setup module (https://docs.ansible.com/ansible/latest/modules/setup_module.html) automatically called by playbooks. Sensing some namespace clashing here, I removed the `collections:` block from the play, and this worked:

```
- name: Configure pfSense
  hosts: pfsense
  remote_user: 'root'
  tasks:
    - name: General setup
      pfsensible.core.setup:
        timezone: America/Chicago
```
I was basing my usage on the example and subsequent comments explaining the new task name changes in #39. So perhaps some documentation clarity would help others avoid the same trap?
