### ISSUE TITLE
When using pfsensible.core.user setting a user to absent that is already removed causes an error

### ISSUE THREAD

**Issue by jay-tuckey** [opoplawski/ansible-pfsense#53]
Using:
pfsense: `2.4.5-RELEASE`
ansible: `2.9.6` on ubuntu 20.04
Installed pfsensible from ansible galaxy using the command: `ansible-galaxy collection install pfsensible.core`

What I'm finding is that if I run the user module, where a user already exists, It's removing the user nicely. However, if I set a user to be removed and the user is already gone, the module errors.

Playbook with users there:
```
- hosts: all
  gather_facts: false
  vars:
    users:
      - name: s123456
        pass: "test"
      - name: s321456
        pass: nextpass
    removeusers:
      - name: s123456
      - name: s321456

  tasks:
  - name: Add users
    pfsensible.core.user:
      name: "{{ item.name }}"
      password: "{{ item.pass| password_hash('bcrypt') }}"
      #password: "{% if defined(item.pass) %}{{ item.pass | password_hash('bcrypt') }}{% endif %}"
    loop: "{{ users }}"
  - name: Remove users
    pfsensible.core.user:
      name: "{{ item.name }}"
      state: absent
    loop: "{{ removeusers }}"
```
run log:
```
~/g/c/pfsense> ansible-playbook -i inventory.ini provision_pfsense_users.yml

PLAY [all] *********************************************************************************************

TASK [Add users] ***************************************************************************************
changed: [pf1] => (item={'name': 's123456', 'pass': 'test'})
changed: [pf1] => (item={'name': 's321456', 'pass': 'nextpass'})
[WARNING]: Platform freebsd on host pf1 is using the discovered Python interpreter at
/usr/local/bin/python3.7, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more
information.

TASK [Remove users] ************************************************************************************
changed: [pf1] => (item={'name': 's123456'})
changed: [pf1] => (item={'name': 's321456'})

PLAY RECAP *********************************************************************************************
pf1                        : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

~/g/c/pfsense>
```

However, this playbook:
```
- hosts: all
  gather_facts: false
  vars:
    users:
      - name: s123456
        pass: "test"
      - name: s321456
        pass: nextpass
    removeusers:
      - name: gonealready

  tasks:
  - name: Add users
    pfsensible.core.user:
      name: "{{ item.name }}"
      password: "{{ item.pass| password_hash('bcrypt') }}"
      #password: "{% if defined(item.pass) %}{{ item.pass | password_hash('bcrypt') }}{% endif %}"
    loop: "{{ users }}"
  - name: Remove users
    pfsensible.core.user:
      name: "{{ item.name }}"
      state: absent
    loop: "{{ removeusers }}"
```
runs like this:
```
~/g/c/pfsense> ansible-playbook -i inventory.ini provision_pfsense_users.yml

PLAY [all] *********************************************************************************************

TASK [Add users] ***************************************************************************************
changed: [pf1] => (item={'name': 's123456', 'pass': 'test'})
changed: [pf1] => (item={'name': 's321456', 'pass': 'nextpass'})
[WARNING]: Platform freebsd on host pf1 is using the discovered Python interpreter at
/usr/local/bin/python3.7, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more
information.

TASK [Remove users] ************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'find'
failed: [pf1] (item={'name': 'gonealready'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "gonealready"}, "module_stderr": "Shared connection to 138.80.128.139 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1591917213.9751663-85254998345163/AnsiballZ_user.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1591917213.9751663-85254998345163/AnsiballZ_user.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1591917213.9751663-85254998345163/AnsiballZ_user.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.pfsensible.core.plugins.modules.user', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_pfsensible.core.user_payload_sa82xwau/ansible_pfsensible.core.user_payload.zip/ansible_collections/pfsensible/core/plugins/modules/user.py\", line 345, in <module>\r\n  File \"/tmp/ansible_pfsensible.core.user_payload_sa82xwau/ansible_pfsensible.core.user_payload.zip/ansible_collections/pfsensible/core/plugins/modules/user.py\", line 336, in main\r\n  File \"/tmp/ansible_pfsensible.core.user_payload_sa82xwau/ansible_pfsensible.core.user_payload.zip/ansible_collections/pfsensible/core/plugins/modules/user.py\", line 277, in remove\r\nAttributeError: 'NoneType' object has no attribute 'find'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************************************
pf1                        : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

It's not a big deal as the user is gone, as mentioned, but thought you would like to know of the bug.
