### ISSUE TITLE
IPSEC cannot use VIP interface

### ISSUE THREAD

**Issue by gaeldb** [opoplawski/ansible-pfsense#57]
Hello everyone,

Issue detected today:
When using a simple WAN CARP VIP, it's not possible to select this VIP as IPSEC interface.
Working in the Pfsense GUI, but not in pfsense_ipsec.
VIP interface are defined like: **_vip5f0eebd19b2ea**

```
failed: [****] {"msg": "_vip5f0eebd19b2ea is not a valid interface"}
```
```
- name: Create IPSEC tunnels (phase 1)
  pfsense_ipsec:
    state: "{{ item.state }}"
    descr: "{{ item.descr }}"
    interface: "_vip5f0eebd19b2ea"
    protocol: inet
    remote_gateway: "{{ item.gateway }}"
    iketype: "{{ item.ike }}"
    mode: main
    authentication_method: pre_shared_key
    preshared_key: "{{ item.key }}"
    myid_type: myaddress
    peerid_type: peeraddress
```

I will investigate this later, but probably a simple "interface name checking" issue?

Thanks
