### ISSUE TITLE
Issues Getting pfsense_alias to work with AWX

### ISSUE THREAD

**Issue by NebraskaCoder** [opoplawski/ansible-pfsense#59]
I have the following playbook (I'm new to Ansible Playbooks, so I may have mistyped something):

```yaml
---
- name: Add RFC1918 Alias
  hosts: all
  collections:
    - pfsensible.core
  tasks:
    - name: Add Alias
      pfsense_alias:
        name: RFC1918
        type: network
        address: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
        state: present
```

I keep getting the following error:

> ERROR! couldn't resolve module/action 'pfsense_alias'. This often indicates a misspelling, missing collection, or incorrect module path.

I have tried creating the following file in both the root of my SCM and inside the directory with my playbook as roles/requirements.yaml

```yaml
---
- src: pfsensible.core
```

Nothing seems to help. Since I'm new, I'm not sure how to get AWX to download the module.

**Comment by opoplawski** [comment]
currently in pfsensible.core the task names do not have the pfsense_ prefix - so try "alias:".  This will likely change in the future...

**Comment by NebraskaCoder** [comment]
My revised code:
```yaml
---
- name: Add RFC1918 Alias
  hosts: all
  collections:
    - pfsensible.core
  tasks:
    - name: Add Alias
      alias:
        name: RFC1918
        type: network
        address: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
        state: present
```
And my revised error:

> ERROR! couldn't resolve module/action 'alias'. This often indicates a misspelling, missing collection, or incorrect module path.

**Comment by NebraskaCoder** [comment]
So, I pulled this out of AWX into a stand-alone playbook as following, making sure to add `gather_facts: no` as it didn't like gathering facts:

```yaml
---
- name: Add RFC1918 Alias
  hosts: all
  gather_facts: no
  collections:
    - pfsensible.core
  tasks:
    - name: Add Alias
      alias:
        name: RFC1918
        type: network
        address: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
        state: present
```

Of course, it works. Sounds like this isn't an issue for you but I need to find someone that can explain why it won't work in AWX and how to correctly import the module.

> PLAY [Add RFC1918 Alias] ********************************************************************************************************************************************************************************************************************
>
>TASK [Add Alias] ****************************************************************************************************************************************************************************************************************************
>[WARNING]: Platform freebsd on host omrtr01p.rootops.net is using the discovered Python interpreter at /usr/local/bin/python3.7, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
changed: [pfsense-router-dns-name]
>
>PLAY RECAP **********************************************************************************************************************************************************************************************************************************
pfsense-router-dns-name       : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by opoplawski** [comment]
I have no experience with AWX so I have no suggestions.

**Comment by NebraskaCoder** [comment]
Thank you anyways.

**Comment by NebraskaCoder** [comment]
In case anybody needs a solution, make a file in your project's directory at `collections/requirements.yml` instead of the roles/requirements.yaml that I was trying to do (also notice that I used yml instead of yaml, that's my second mistake). In that file, put the following:

```yaml
---
collections:
  - name: pfsensible.core
```

And my playbook is below. Notice that I put `gather_facts: no` so that the playbook doesn't crash. I also had to suppress a warning about python by adding an inventory variable with `ansible_python_interpreter: auto_silent`:

```yaml
---
- name: Add RFC1918 Alias
  hosts: all
  gather_facts: no
  collections:
    - pfsensible.core
  tasks:
    - name: Add Alias
      alias:
        name: RFC1918
        type: network
        address: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
        state: present
```
