### ISSUE TITLE
diff['before'] is equal to diff['after']

### ISSUE THREAD

**Issue by coffeelover** [opoplawski/ansible-pfsense#73]
While doing module developement, I noticed that at least for the setup module the diff in verbose mode is wrong.

Given the simple playbook
```
---
- name: Set pfsense general settings
  hosts: all
  collections:
    - "pfsensible.core"
  tasks:
    - name: Set dashboardcolumns
      pfsense_setup:
        dashboardcolumns: 6
```

`$ ansible-playbook -C -vvv setup.yml` gives the following output:

```
changed: [firewall.example.com] => {
    "changed": true,
    "commands": [
        "update setup general set dns_addresses=none, dashboardcolumns='6'"
    ],
    "diff": {
        "after": {
[...]
            "webgui": {
                "dashboardcolumns": "6",
[...]
            }
        },
        "before": {
            "webgui": {
                "dashboardcolumns": "6",
[...]
            }
        }
    },
[...]
```

**Cause:**
https://github.com/opoplawski/ansible-pfsense/blob/master/module_utils/network/pfsense/module_base.py#L124

**Explanation:** 

1. `self.obj` is modified by `_obj_to_param`
(https://github.com/opoplawski/ansible-pfsense/blob/master/library/pfsense_setup.py#L468)

2. `_add` is called as a super method
(https://github.com/opoplawski/ansible-pfsense/blob/master/library/pfsense_setup.py#L470)

3. `_add` calls `_copy_and_update_target`
(https://github.com/opoplawski/ansible-pfsense/blob/master/module_utils/network/pfsense/module_base.py#L124)
  uses `self.obj` as before dict

At least in the setup module a `self.before` is constructed which can be used successfully.
(https://github.com/opoplawski/ansible-pfsense/blob/master/library/pfsense_setup.py#L279)
